/**
 * README Generator for ArchMe
 * 
 * Generates installation and setup instructions based on generated code
 */

import type { GeneratedCode } from './code-generator';

export interface ReadmeContent {
  title: string;
  description: string;
  installation: string;
  prerequisites: string[];
  usage: string;
  components: Array<{
    name: string;
    type: string;
    description: string;
  }>;
}

/**
 * Generate README content from generated code
 */
export function generateReadme(generatedCode: GeneratedCode[]): string {
  const components = generatedCode.map(code => ({
    name: code.componentName,
    type: code.codeType,
    description: code.description
  }));

  // Detect prerequisites based on code types
  const prerequisites = new Set<string>();
  const hasTerraform = generatedCode.some(c => c.codeType === 'terraform');
  const hasKubernetes = generatedCode.some(c => c.codeType === 'kubernetes' || c.codeType === 'yaml');
  const hasHelm = generatedCode.some(c => c.codeType === 'helm');
  const hasARM = generatedCode.some(c => c.codeType === 'arm');

  if (hasTerraform) {
    prerequisites.add('Terraform >= 1.0');
    // Detect which cloud providers are actually used by scanning generated Terraform content
    const tfContent = generatedCode
      .filter(c => c.codeType === 'terraform')
      .map(c => c.content)
      .join('\n')
      .toLowerCase();
    if (tfContent.includes('azurerm') || tfContent.includes('provider "azurerm"')) {
      prerequisites.add('Azure CLI');
    }
    if (tfContent.includes('provider "aws"') || /\baws_/.test(tfContent)) {
      prerequisites.add('AWS CLI');
    }
    if (tfContent.includes('provider "google"') || /\bgoogle_/.test(tfContent)) {
      prerequisites.add('Google Cloud SDK (gcloud)');
    }
  }
  if (hasKubernetes) {
    prerequisites.add('kubectl');
    prerequisites.add('Kubernetes cluster access');
  }
  if (hasHelm) {
    prerequisites.add('Helm >= 3.0');
  }
  if (hasARM) {
    prerequisites.add('Azure CLI');
    prerequisites.add('Azure subscription');
  }

  // Generate installation steps
  let installationSteps = '';
  
  if (hasTerraform) {
    installationSteps += `## Terraform Resources

\`\`\`bash
# Initialize Terraform
terraform init

# Review the execution plan
terraform plan

# Apply the configuration
terraform apply
\`\`\`

`;
  }

  if (hasKubernetes) {
    installationSteps += `## Kubernetes Resources

\`\`\`bash
# Apply Kubernetes manifests
kubectl apply -f *.yaml

# Verify deployment
kubectl get pods,services
\`\`\`

`;
  }

  if (hasHelm) {
    installationSteps += `## Helm Charts

\`\`\`bash
# Install Helm chart
helm install <release-name> ./chart

# Or upgrade existing release
helm upgrade <release-name> ./chart
\`\`\`

`;
  }

  if (hasARM) {
    installationSteps += `## ARM Templates

\`\`\`bash
# Deploy ARM template
az deployment group create \\
  --resource-group <resource-group-name> \\
  --template-file <template-file>.json \\
  --parameters @<parameters-file>.json
\`\`\`

`;
  }

  // Generate component list
  const componentList = components.map(comp => {
    return `### ${comp.name}
- **Type**: ${comp.type}
- **Description**: ${comp.description}
- **File**: \`${generatedCode.find(c => c.componentName === comp.name)?.fileName || 'N/A'}\`
`;
  }).join('\n');

  const readme = `# Infrastructure Setup

This repository contains infrastructure code generated by ArchMe.

## Overview

This infrastructure includes ${components.length} component(s):
${components.map(c => `- ${c.name} (${c.type})`).join('\n')}

## Prerequisites

Before deploying this infrastructure, ensure you have the following installed:

${Array.from(prerequisites).map(p => `- ${p}`).join('\n')}

## Installation

${installationSteps}

## Components

${componentList}

## Notes

- Review all configuration files before deployment
- Ensure you have appropriate permissions in your cloud provider
- Some resources may require manual configuration after deployment
- Check the individual component files for specific requirements

## Support

For issues or questions, please refer to the component-specific documentation or contact your infrastructure team.
`;

  return readme;
}


